{{- if .Values.reportsController.enabled -}}
{{- if .Values.reportsController.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno.reports-controller.roleName" . }}
  labels:
    {{- include "kyverno.reports-controller.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.kyverno.io/aggregate-to-reports-controller: "true"
    - matchLabels:
        {{- include "kyverno.reports-controller.matchLabels" . | nindent 8 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno.reports-controller.roleName" . }}:core
  labels:
    {{- include "kyverno.reports-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - configmaps
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kyverno.io
    resources:
      - globalcontextentries
      - globalcontextentries/status
      - policyexceptions
      - policies
      - clusterpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - reports.kyverno.io
    resources:
      - ephemeralreports
      - clusterephemeralreports
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - wgpolicyk8s.io
    resources:
      - policyreports
      - policyreports/status
      - clusterpolicyreports
      - clusterpolicyreports/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups: [""]  
    resources:
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]  
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]  
    resources:
      - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ''
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
{{- with .Values.reportsController.rbac.coreClusterRole.extraResources }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.reportsController.rbac.clusterRole.extraResources }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno.reports-controller.roleName" $ }}:additional
  labels:
    {{- include "kyverno.reports-controller.labels" $ | nindent 4 }}
rules:
  {{- range . }}
  - apiGroups:
      {{- toYaml .apiGroups | nindent 6 }}
    resources:
      {{- toYaml .resources | nindent 6 }}
    verbs:
      - get
      - list
      - watch
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-nirmata-reports-controller-role ## additional cluster-role for Razorpay clusters
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - "clusterroles"
    - "clusterrolebindings"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups: ["traefik.io"]
  resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kafka.strimzi.io"]
  resources: ["kafkatopics"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["flowcontrol.apiserver.k8s.io"]
  resources:
    - "flowschemas"
    - "prioritylevelconfigurations"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups: ["storage.k8s.io"]
  resources:
    - "csistoragecapacities"
  verbs:
    - "get"
    - "list"
    - "watch"
